### ISSUE TITLE
[build] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by silverjungohoh** [CRUDE-HI/travel-crew-practice#2]
## 📌설명
> build.gradle에 필요한 dependency 추가
querydsl 사용 위한 설정

## 🗒️Todo
- [ ] spring security 관련 dependency 추가
- [ ] 메일 전송을 위한 dependency 추가
- [ ] 채팅 기능 구현 위한 dependency 추가
- [ ] querydsl 사용 위한 설정 작성
- [ ] application.properties 작성
